export {default as BreadcrumbsStatic} from './BreadcrumbsStatic.vue'
export * from './tabs'
export {default as LoadingSpinner} from './LoadingSpinner.vue'
export {default as SnackbarGeneral} from './SnackbarGeneral.vue'
export {default as ConfirmDialog} from './ConfirmDialog.vue'